#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  vim:ts=4:sts=4:sw=4:et

language: perl
perl:
  - "5.22"
  # this build has thread support
  - "5.18-shrplib"
  #- "5.16"
  # latest Redis cpan module requires Perl >= 5.10
  - "5.10"
  # there is workaround in build now to install older version if latest fails for RHEL5/CentOS5 servers
  # other CPAN modules are broken for Perl 5.8, re-visit
  #- "5.8"

sudo: required

notifications:
  email: false

install:
  #- pushd lib
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM LIB FAILED
  #- popd
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM FAILED
  # integrated cpanm in to core Makefiles
  # workaround for strange error when building pylib submodule
  - sudo chmod -R 777 /opt/python /usr/local/lib
  - make
  - make zookeeper

script:
  - tests/all.sh

services:
  #- docker
  - cassandra
  #- couchdb
  - elasticsearch
  - memcached
  - mongodb
  - mysql
  #- postgreql
  - neo4j
  #- rabbitmq
  - redis
  - riak

env:
  global:
    - MYSQL_DATABASE=mysql
    - MYSQL_PASSWORD=""
    - MYSQL_USER=travis
