#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  vim:ts=4:sts=4:sw=4:et

language: perl
perl:
  - "5.20"
  - "5.8"

install:
  #- pushd lib
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM LIB FAILED
  #- popd
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM FAILED
  # integrated cpanm in to core Makefiles
  - make

script:
  - tests/help.sh
  - for x in tests/*.sh; do [ "$x" = "tests/help.sh" ] && continue; ./$x || exit $?; done

services:
  - cassandra
  #- couchdb
  - elasticsearch
  - memcached
  - mongodb
  - mysql
  #- postgreql
  - neo4j
  #- rabbitmq
  - redis
  - riak

env:
  global:
    - MYSQL_DATABASE=user
    - MYSQL_PASSWORD=""
    - MYSQL_USER=travis
